/**
 * Paper upload test: register a fresh agent, join sciencesubs, then verify
 * publishPaperToAgent4Science sends the correct payload to the API.
 *
 * By default the createPaper HTTP call is intercepted with a spy so no real
 * paper is created on the platform (the API has no DELETE endpoint for papers).
 * Steps 1+2 use the real API; the agent is deleted on cleanup.
 *
 * To do a real end-to-end write (will leave a paper on the platform):
 *   E2E_REAL_PAPER=1 npx vitest run tests/challenges/e2e-paper-upload.test.ts
 *
 * Run (default, no platform pollution):
 *   npx vitest run tests/challenges/e2e-paper-upload.test.ts
 * Skip entirely:
 *   E2E_SKIP=1 npx vitest run tests/challenges/e2e-paper-upload.test.ts
 */
import { describe, it, expect, beforeAll, vi, afterAll } from 'vitest';
import { Agent4ScienceClient, createAgent4ScienceClient } from '../../src/api/agent4science-client.js';
import { publishPaperToAgent4Science } from '../../src/tools/paper-tools.js';
import type { Agent4SciencePaper } from '../../src/types.js';

const BASE_URL = process.env.A4S_BASE_URL || 'https://agent4science.org';
const SKIP = process.env.E2E_SKIP === '1';
const REAL_PAPER = process.env.E2E_REAL_PAPER === '1';

const describeE2E = SKIP ? describe.skip : describe;

async function fetchRetry(url: string, init?: RequestInit, retries = 3): Promise<Response> {
  for (let i = 0; i < retries; i++) {
    try { return await fetch(url, init); } catch (err) {
      if (i === retries - 1) throw err;
      await new Promise(r => setTimeout(r, 2000 * (i + 1)));
    }
  }
  throw new Error('unreachable');
}

const PAPER_PARAMS = {
  title: 'Flamebird E2E Test Paper: Automated Paper Upload Verification',
  abstract: [
    'This paper is an automated end-to-end test artifact generated by the Flamebird',
    'integration test suite. It verifies that the publishPaperToAgent4Science function',
    'correctly constructs and sends a paper creation request to the Agent4Science API,',
    'and that the API accepts all required fields and returns a valid paper ID.',
    'The paper contains no real research content and should be deleted immediately',
    'after the test completes as part of automated cleanup.',
  ].join(' '),
  tldr: 'Automated test artifact verifying the paper upload path in the Flamebird runtime.',
  hypothesis: 'The publishPaperToAgent4Science function correctly uploads papers to Agent4Science when all required fields meet API constraints.',
  conclusion: 'If this paper exists in the system, the upload path is working correctly end-to-end.',
  experimentPlan: 'Call publishPaperToAgent4Science with valid params and assert a paper ID is returned.',
  claims: [
    'The paper upload function sends all required fields to the API.',
    'The API returns a valid paper ID on success.',
    'The uploaded paper can be fetched by its returned ID.',
  ],
  limitations: ['This is a test artifact with no real research content.'],
  githubUrl: 'https://github.com/agentforscience/flamebird',
  pdfUrl: 'https://github.com/agentforscience/flamebird/blob/main/README.md',
} as const;

let client: Agent4ScienceClient;
let apiKey = '';
let agentHandle = '';
let firstSubSlug = '';

beforeAll(() => {
  client = createAgent4ScienceClient({ baseUrl: BASE_URL, timeout: 30000 });
});

afterAll(() => {
  vi.restoreAllMocks();
});

describeE2E('paper upload via publishPaperToAgent4Science', () => {

  // ── Step 1: Register test agent ───────────────────────────────────────────
  it('1. registers a fresh test agent', async () => {
    const handle = `paperbot_${Date.now().toString(36)}`;
    const res = await fetchRetry(`${BASE_URL}/api/v1/agents/create`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        handle,
        displayName: `Paper Upload Test Bot ${handle}`,
        bio: 'Throwaway agent created by the flamebird paper-upload test. Will be deleted on cleanup.',
        persona: {
          voice: 'academic', epistemics: 'rigorous', spiceLevel: 2,
          petPeeves: [], preferredTopics: ['machine-learning'], catchphrases: [],
        },
      }),
    });
    expect(res.ok).toBe(true);
    const data = await res.json();
    expect(data.success).toBe(true);
    expect(data.apiKey).toBeTruthy();
    apiKey = data.apiKey;
    agentHandle = handle;
    console.log(`✓ Registered @${agentHandle}`);
  }, 20000);

  // ── Step 2: Join sciencesubs ──────────────────────────────────────────────
  it('2. joins at least 5 sciencesubs (required before publishing)', async () => {
    expect(apiKey).toBeTruthy();
    const subsResult = await client.getSciencesubs(apiKey);
    expect(subsResult.success).toBe(true);
    const subs = subsResult.data || [];
    expect(subs.length).toBeGreaterThanOrEqual(5);
    const toJoin = subs.slice(0, 5);
    firstSubSlug = toJoin[0].slug;
    let joined = 0;
    for (const sub of toJoin) {
      const r = await client.joinSciencesub(sub.slug, apiKey);
      if (r.success || (r as any).code === 'ALREADY_MEMBER') joined++;
    }
    expect(joined).toBeGreaterThanOrEqual(5);
    console.log(`✓ Joined ${joined} sciencesubs, first tag will be "${firstSubSlug}"`);
  }, 30000);

  // ── Step 3: Upload paper (mocked by default, real with E2E_REAL_PAPER=1) ──
  it('3. calls publishPaperToAgent4Science with correct payload', async () => {
    expect(apiKey).toBeTruthy();
    expect(firstSubSlug).toBeTruthy();

    const params = { ...PAPER_PARAMS, tags: [firstSubSlug, 'testing', 'automation'] };

    let createPaperSpy: ReturnType<typeof vi.spyOn> | null = null;

    if (!REAL_PAPER) {
      // Spy on client.createPaper — same singleton getAgent4ScienceClient() returns.
      // Returns a realistic mock so no paper is written to the platform.
      createPaperSpy = vi.spyOn(client, 'createPaper').mockResolvedValueOnce({
        success: true,
        data: { id: 'paper_mock_test', title: params.title, tags: params.tags } as Agent4SciencePaper,
      });
    }

    const result = await publishPaperToAgent4Science(apiKey, params);

    expect(result.success).toBe(true);
    expect(result.data?.id).toBeTruthy();

    if (createPaperSpy) {
      // Verify the function passed the full correct payload through to createPaper
      expect(createPaperSpy).toHaveBeenCalledOnce();
      expect(createPaperSpy).toHaveBeenCalledWith(
        expect.objectContaining({
          title: PAPER_PARAMS.title,
          githubUrl: PAPER_PARAMS.githubUrl,
          pdfUrl: PAPER_PARAMS.pdfUrl,
          tags: [firstSubSlug, 'testing', 'automation'],
          claims: expect.arrayContaining([PAPER_PARAMS.claims[0]]),
        }),
        apiKey,
      );
      console.log(`✓ createPaper called with correct payload (mocked — no paper written to platform)`);
    } else {
      console.log(`✓ Paper uploaded for real: ${result.data!.id} — NOTE: cannot be deleted (API 405)`);
    }
  }, 30000);

  // ── Step 4: Payload field-length constraints ──────────────────────────────
  it('4. all field lengths satisfy API constraints', () => {
    // title: min 10, max 200
    expect(PAPER_PARAMS.title.length).toBeGreaterThanOrEqual(10);
    expect(PAPER_PARAMS.title.length).toBeLessThanOrEqual(200);
    // abstract: min 100, max 5000
    expect(PAPER_PARAMS.abstract.length).toBeGreaterThanOrEqual(100);
    expect(PAPER_PARAMS.abstract.length).toBeLessThanOrEqual(5000);
    // tldr: min 30, max 1000
    expect(PAPER_PARAMS.tldr.length).toBeGreaterThanOrEqual(30);
    expect(PAPER_PARAMS.tldr.length).toBeLessThanOrEqual(1000);
    // hypothesis: min 10, max 3000
    expect(PAPER_PARAMS.hypothesis.length).toBeGreaterThanOrEqual(10);
    expect(PAPER_PARAMS.hypothesis.length).toBeLessThanOrEqual(3000);
    // conclusion: min 10, max 3000
    expect(PAPER_PARAMS.conclusion.length).toBeGreaterThanOrEqual(10);
    expect(PAPER_PARAMS.conclusion.length).toBeLessThanOrEqual(3000);
    // URLs must be https
    expect(PAPER_PARAMS.githubUrl).toMatch(/^https:\/\//);
    expect(PAPER_PARAMS.pdfUrl).toMatch(/^https:\/\//);
    // claims: at least 1
    expect(PAPER_PARAMS.claims.length).toBeGreaterThanOrEqual(1);
    console.log('✓ All field lengths satisfy API constraints');
  });

  // ── Cleanup ───────────────────────────────────────────────────────────────
  it('cleanup: deletes the test agent', async () => {
    if (!apiKey) return;
    const res = await fetchRetry(`${BASE_URL}/api/v1/agents/me`, {
      method: 'DELETE',
      headers: { 'Authorization': `Bearer ${apiKey}` },
    });
    expect([200, 204, 404]).toContain(res.status);
    console.log(`✓ Deleted @${agentHandle}`);
  }, 10000);
});
