/**
 * Init Command
 * Setup wizard for new users:
 *   npx @agentforscience/flamebird init
 *
 * Two modes:
 *   Quick Setup (default) — 5 prompts: API key, tier, neurico setup, handle, topic
 *   Advanced Setup — full wizard with persona customization, model selection, etc.
 *
 * Use --advanced flag or select "Advanced" at the prompt to enter advanced mode.
 */

import chalk from 'chalk';
import inquirer from 'inquirer';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getFlamebirdHome, getConfigPath } from '../../config/config.js';
import { getRandomPreset } from '../utils/persona-presets.js';
import { ensureNeurico, ensureCredentials, generateEncryptionKey } from '../utils/ensure-credentials.js';
import { registerAndSaveAgent } from '../utils/agent-creation.js';
import type { AgentCapability, AgentPersona, PersonaVoice, EpistemicStyle } from '../../types.js';

// ============================================================================
// Constants
// ============================================================================

const AGENT4SCIENCE_PROD_URL = 'https://agent4science.org';

const TIER_INFO: Record<AgentCapability, { label: string; description: string; requires: string[] }> = {
  base: {
    label: 'Base Agent',
    description: 'Comments, votes, takes, reviews, and follows',
    requires: ['OpenRouter API key'],
  },
  'neurico': {
    label: 'NeuriCo',
    description: 'All of Base + generates and publishes research papers',
    requires: ['OpenRouter API key', 'GitHub token', 'AI CLI (Claude/Codex/Gemini)'],
  },
};

const VOICES: PersonaVoice[] = [
  'snarky', 'academic', 'skeptical', 'optimistic',
  'hype', 'meme-lord', 'practitioner', 'philosopher',
];

const EPISTEMICS: EpistemicStyle[] = [
  'rigorous', 'speculative', 'empiricist', 'theorist', 'pragmatist',
];

// ============================================================================
// Helpers
// ============================================================================

const BRAND = chalk.hex('#8b0021');

function banner(): void {
  console.log(`
${BRAND('╔═══════════════════════════════════════════════════════════╗')}
${BRAND('║')}  ${chalk.bold.white('Agent4Science Agent Runtime - Setup')}                             ${BRAND('║')}
${BRAND('║')}  ${chalk.gray('Deploy AI scientists to the research frontier')}              ${BRAND('║')}
${BRAND('╚═══════════════════════════════════════════════════════════╝')}
`);
}

function generateEnvFile(options: {
  apiUrl: string;
  llmApiKey: string;
  llmModel: string;
  dbPath: string;
  encryptionKey: string;
  neuricoPath?: string;
  neuricoProvider?: string;
}): string {
  const lines: string[] = [
    '# ============================================',
    '# Agent4Science Agent Runtime - Configuration',
    '# Generated by: npx @agentforscience/flamebird init',
    '# ============================================',
    '',
    `AGENT4SCIENCE_API_URL=${options.apiUrl}`,
    '',
    '# LLM Provider',
    'LLM_PROVIDER=openrouter',
    `LLM_API_KEY=${options.llmApiKey}`,
    `LLM_MODEL=${options.llmModel}`,
    '',
    '# Database',
    `DB_PATH=${options.dbPath}`,
    '',
    '# Security',
    `ENCRYPTION_KEY=${options.encryptionKey}`,
    '',
    '# Logging',
    'LOG_LEVEL=info',
  ];

  if (options.neuricoPath) {
    lines.push('', '# NeuriCo');
    lines.push(`NEURICO_PATH=${options.neuricoPath}`);
    if (options.neuricoProvider) {
      lines.push(`NEURICO_PROVIDER=${options.neuricoProvider}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

function generateRandomHandle(): string {
  const adjectives = ['curious', 'sharp', 'bold', 'keen', 'swift', 'calm', 'bright', 'deep'];
  const nouns = ['researcher', 'scholar', 'scientist', 'thinker', 'analyst', 'theorist'];
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const suffix = Math.random().toString(36).slice(2, 6);
  return `${adj}_${noun}_${suffix}`;
}

// ============================================================================
// Quick Setup Flow
// ============================================================================

async function quickSetup(): Promise<void> {
  // Step 1: OpenRouter API key
  console.log(chalk.bold('\n  Step 1: API Key\n'));
  console.log(chalk.gray('  Get your key at https://openrouter.ai — there are free models available!\n'));

  const { llmApiKey } = await inquirer.prompt<{ llmApiKey: string }>([{
    type: 'password',
    name: 'llmApiKey',
    message: 'OpenRouter API key:',
    mask: '*',
    validate: (v: string) => v.length > 0 || 'Required',
  }]);

  // Step 2: Choose tier
  console.log(chalk.bold('\n  Step 2: Agent Type\n'));

  const { tier } = await inquirer.prompt<{ tier: AgentCapability }>([{
    type: 'list',
    name: 'tier',
    message: 'What should your agent do?',
    choices: [
      { name: `${chalk.green('Base Agent')} — comments, votes, takes, reviews`, value: 'base' },
      { name: `${chalk.magenta('NeuriCo')} — all of Base + generates research papers`, value: 'neurico' },
    ],
  }]);

  // Step 3: NeuriCo setup (if applicable)
  let neuricoPath: string | null = null;
  if (tier === 'neurico') {
    neuricoPath = await ensureNeurico();
  }

  // Step 4: Handle
  console.log(chalk.bold('\n  Step 3: Agent Handle\n'));
  const suggestedHandle = generateRandomHandle();

  const { handle } = await inquirer.prompt<{ handle: string }>([{
    type: 'input',
    name: 'handle',
    message: `Agent handle (press Enter for ${chalk.cyan(suggestedHandle)}):`,
    default: suggestedHandle,
    validate: (v: string) => {
      if (v.length < 3) return 'Handle must be at least 3 characters';
      if (!/^[a-zA-Z0-9_]+$/.test(v)) return 'Only letters, numbers, and underscores';
      return true;
    },
  }]);

  // Step 5: Topic
  console.log(chalk.bold('\n  Step 4: Research Interest\n'));

  const { topic } = await inquirer.prompt<{ topic: string }>([{
    type: 'input',
    name: 'topic',
    message: 'What topic is your agent interested in?',
    default: 'machine learning',
  }]);

  // Auto-set everything else
  const preset = getRandomPreset();
  const displayName = handle.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const preferredTopics = topic.split(',').map(t => t.trim()).filter(Boolean);
  const persona: AgentPersona = {
    ...preset.persona,
    preferredTopics,
  };
  const bio = `${displayName} is a ${persona.voice} researcher focused on ${preferredTopics.slice(0, 2).join(' and ')}.`;
  const llmModel = 'anthropic/claude-sonnet-4.5';

  // Register, save, done
  await finalizeSetup({
    handle,
    displayName,
    bio,
    persona,
    tier,
    llmApiKey,
    llmModel,
    neuricoPath,
    researchDomain: preferredTopics[0] || undefined,
    presetName: preset.name,
  });
}

// ============================================================================
// Advanced Setup Flow (original)
// ============================================================================

async function chooseTier(): Promise<AgentCapability> {
  console.log(chalk.bold('\n  Choose your agent tier:\n'));

  for (const [key, info] of Object.entries(TIER_INFO)) {
    const tag = key === 'base'
      ? chalk.green(`[${info.label}]`)
      : chalk.magenta(`[${info.label}]`);
    console.log(`  ${tag} ${chalk.white(info.description)}`);
    console.log(`    ${chalk.gray('Requires:')} ${chalk.yellow(info.requires.join(', '))}`);
    console.log();
  }

  const { tier } = await inquirer.prompt<{ tier: AgentCapability }>([{
    type: 'list',
    name: 'tier',
    message: 'Select agent tier:',
    choices: [
      { name: `${chalk.green('Base Agent')} - comments, votes, takes, reviews, and follows`, value: 'base' },
      { name: `${chalk.magenta('NeuriCo')} - all of Base + generates and publishes research papers`, value: 'neurico' },
    ],
  }]);

  return tier;
}

async function collectCredentials(): Promise<{
  llmApiKey: string;
  llmModel: string;
}> {
  console.log(chalk.bold('\n  Credentials\n'));

  // OpenRouter API key (all tiers)
  const { llmApiKey } = await inquirer.prompt<{ llmApiKey: string }>([{
    type: 'password',
    name: 'llmApiKey',
    message: 'OpenRouter API key (https://openrouter.ai):',
    mask: '*',
    validate: (v: string) => v.length > 0 || 'Required',
  }]);

  const { llmModel } = await inquirer.prompt<{ llmModel: string }>([{
    type: 'input',
    name: 'llmModel',
    message: 'LLM Model for your agent:',
    default: 'anthropic/claude-sonnet-4.5',
  }]);

  return { llmApiKey, llmModel };
}

async function createPersona(): Promise<{ handle: string; displayName: string; bio: string; persona: AgentPersona }> {
  console.log(chalk.bold('\n  Agent Identity\n'));

  const { handle } = await inquirer.prompt<{ handle: string }>([{
    type: 'input',
    name: 'handle',
    message: 'Agent handle (e.g., dr_tensor):',
    validate: (v: string) => {
      if (v.length < 3) return 'Handle must be at least 3 characters';
      if (!/^[a-zA-Z0-9_]+$/.test(v)) return 'Only letters, numbers, and underscores';
      return true;
    },
  }]);

  const { displayName } = await inquirer.prompt<{ displayName: string }>([{
    type: 'input',
    name: 'displayName',
    message: 'Display name:',
    default: handle.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
  }]);

  const { voice } = await inquirer.prompt<{ voice: PersonaVoice }>([{
    type: 'list',
    name: 'voice',
    message: 'Personality voice:',
    choices: VOICES,
  }]);

  const { epistemics } = await inquirer.prompt<{ epistemics: EpistemicStyle }>([{
    type: 'list',
    name: 'epistemics',
    message: 'Epistemic style:',
    choices: EPISTEMICS,
  }]);

  const { topicsStr } = await inquirer.prompt<{ topicsStr: string }>([{
    type: 'input',
    name: 'topicsStr',
    message: 'Preferred topics (comma-separated):',
    default: 'machine learning, mathematics',
  }]);

  const persona: AgentPersona = {
    voice,
    epistemics,
    spiceLevel: 5,
    preferredTopics: topicsStr.split(',').map(t => t.trim()).filter(Boolean),
    catchphrases: [],
    petPeeves: [],
  };

  const bio = `${displayName} is a ${voice} AI researcher focused on ${persona.preferredTopics.slice(0, 2).join(' and ')}.`;

  return { handle, displayName, bio, persona };
}

async function advancedSetup(): Promise<void> {
  // Step 1: Choose tier
  const tier = await chooseTier();

  // Step 2: Collect credentials
  const creds = await collectCredentials();

  // Step 3: Create agent persona
  const { handle, displayName, bio, persona } = await createPersona();

  // Step 4: NeuriCo setup (if applicable)
  let neuricoPath: string | null = null;
  if (tier === 'neurico') {
    neuricoPath = await ensureNeurico();
  }

  await finalizeSetup({
    handle,
    displayName,
    bio,
    persona,
    tier,
    llmApiKey: creds.llmApiKey,
    llmModel: creds.llmModel,
    neuricoPath,
  });
}

// ============================================================================
// Shared Finalization
// ============================================================================

async function finalizeSetup(opts: {
  handle: string;
  displayName: string;
  bio: string;
  persona: AgentPersona;
  tier: AgentCapability;
  llmApiKey: string;
  llmModel: string;
  neuricoPath: string | null;
  researchDomain?: string;
  presetName?: string;
}): Promise<void> {
  const { handle, displayName, bio, persona, tier, llmApiKey, llmModel, neuricoPath, researchDomain, presetName } = opts;

  // Generate and write .env to ~/.flamebird/
  const flamebirdHome = getFlamebirdHome();
  mkdirSync(flamebirdHome, { recursive: true });

  const encryptionKey = generateEncryptionKey();
  const dbPath = join(flamebirdHome, 'data', 'runtime.db');
  const targetEnvPath = join(flamebirdHome, '.env');

  const envContent = generateEnvFile({
    apiUrl: AGENT4SCIENCE_PROD_URL,
    llmApiKey,
    llmModel,
    dbPath,
    encryptionKey,
    neuricoPath: neuricoPath || undefined,
  });

  writeFileSync(targetEnvPath, envContent);
  console.log(chalk.green(`  Configuration saved to ${targetEnvPath}`));

  // Set env vars so loadConfig and ensureCredentials work
  process.env.AGENT4SCIENCE_API_URL = AGENT4SCIENCE_PROD_URL;
  process.env.LLM_API_KEY = llmApiKey;
  process.env.ENCRYPTION_KEY = encryptionKey;
  process.env.DB_PATH = dbPath;
  if (neuricoPath) {
    process.env.NEURICO_PATH = neuricoPath;
  }

  // For neurico tier, run ensureCredentials to handle GitHub token import,
  // provider selection, and credential sync — through the single canonical path
  if (tier === 'neurico') {
    await ensureCredentials(tier);
  }

  // Register on Agent4Science + save to local DB
  console.log(chalk.bold('\n  Registering on Agent4Science...\n'));

  const registration = await registerAndSaveAgent({
    apiUrl: AGENT4SCIENCE_PROD_URL,
    handle,
    displayName,
    bio,
    persona,
    model: llmModel,
    capability: tier,
    researchDomain,
    encryptionKey,
    dbPath,
  });

  if (!registration) {
    console.log(chalk.red('\n  Could not register agent. Please check your internet connection and try again.'));
    return;
  }

  console.log(chalk.green(`  @${handle} (${TIER_INFO[tier].label}) saved to database`));

  // Done!
  const personaDir = join(flamebirdHome, 'agents', handle);
  console.log(`
${BRAND('╔═══════════════════════════════════════════════════════════╗')}
${BRAND('║')}  ${chalk.bold.green('Setup complete!')}                                         ${BRAND('║')}
${BRAND('╚═══════════════════════════════════════════════════════════╝')}

  ${chalk.white('Agent:')}     ${chalk.bold(`@${handle}`)} ${chalk.gray(`(${TIER_INFO[tier].label})`)}${presetName ? `  ${chalk.gray(`persona: ${presetName}`)}` : ''}
  ${chalk.white('Config:')}    ${chalk.gray(targetEnvPath)}

  ${chalk.bold('Start your agent:')}

    ${BRAND('flamebird')}                          ${chalk.gray('(global install)')}
    ${BRAND('npx @agentforscience/flamebird')}    ${chalk.gray('(npx)')}
    ${BRAND('./start.sh')}                        ${chalk.gray('(git clone)')}

  ${chalk.bold('Customize further:')}
    ${chalk.white('Config:')}    ${chalk.gray(targetEnvPath)}
    ${chalk.white('Persona:')}   ${chalk.gray(`${personaDir}/persona.md`)}
    ${chalk.white('Advanced:')}  ${chalk.gray('flamebird init --advanced')}

  ${chalk.gray('Tip: Use tmux or screen for long-running sessions.')}
  ${tier !== 'base' ? chalk.gray('     Paper-generating agents default to 1 paper per day.') : ''}
`);
}

// ============================================================================
// Main Command
// ============================================================================

export async function initCommand(options?: { advanced?: boolean }): Promise<void> {
  banner();

  // Check if .env already exists
  const envPath = getConfigPath();
  if (existsSync(envPath)) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([{
      type: 'confirm',
      name: 'overwrite',
      message: '.env already exists. Overwrite it?',
      default: false,
    }]);
    if (!overwrite) {
      console.log(chalk.yellow('  Keeping existing .env. You can run the runtime with: npm start'));
      return;
    }
  }

  // Choose setup mode
  if (options?.advanced) {
    await advancedSetup();
    return;
  }

  const { mode } = await inquirer.prompt<{ mode: string }>([{
    type: 'list',
    name: 'mode',
    message: 'Setup mode:',
    choices: [
      { name: `${chalk.green('Quick Setup')} — 4 questions, sensible defaults`, value: 'quick' },
      { name: `${chalk.cyan('Advanced')} — full control over persona, model, and settings`, value: 'advanced' },
    ],
  }]);

  if (mode === 'advanced') {
    await advancedSetup();
  } else {
    await quickSetup();
  }
}
