/**
 * Setup for Production
 * Interactive wizard to connect the runtime to a live Agent4Science instance.
 * Writes .env so others can get started in a few steps.
 */

import chalk from 'chalk';
import fs from 'fs';
import inquirer from 'inquirer';
import { getConfigPath } from '../../config/config.js';

const DEFAULT_PRODUCTION_URL = 'https://agent4science.org';

function randomEncryptionKey(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let s = '';
  for (let i = 0; i < 32; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

function loadExistingEnv(): Record<string, string> {
  const envPath = getConfigPath();
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, 'utf-8');
  const out: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    out[key] = value;
  }
  return out;
}

function writeEnv(vars: Record<string, string>): void {
  const envPath = getConfigPath();
  const lines = [
    '# Agent4Science Agent Runtime – production',
    '# Generated by: flamebird setup-production',
    '',
    ...Object.entries(vars).map(([k, v]) => `${k}=${v}`),
  ];
  fs.writeFileSync(envPath, lines.join('\n') + '\n');
}

export async function setupProductionCommand(): Promise<void> {
  console.log(chalk.cyan('\n  ╔══════════════════════════════════════════════════════╗'));
  console.log(chalk.cyan('  ║') + chalk.bold.white('  🔧 Configure Environment – connect to Agent4Science            ') + chalk.cyan('║'));
  console.log(chalk.cyan('  ╚══════════════════════════════════════════════════════╝\n'));
  console.log(chalk.gray('  We’ll create or update your .env so the runtime talks to a live Agent4Science.\n'));

  const existing = loadExistingEnv();

  const { apiUrl } = await inquirer.prompt([
    {
      type: 'input',
      name: 'apiUrl',
      message: chalk.white('Agent4Science URL (your production or shared instance):'),
      default: existing.AGENT4SCIENCE_API_URL || DEFAULT_PRODUCTION_URL,
      prefix: '  🌍 ',
    },
  ]);

  const { encryptionKeyChoice } = await inquirer.prompt([
    {
      type: 'list',
      name: 'encryptionKeyChoice',
      message: chalk.white('Encryption key (protects stored agent API keys):'),
      choices: [
        { name: 'Generate a new one for me', value: 'generate' },
        { name: "I'll paste my own (min 16 characters)", value: 'paste' },
        { name: 'Keep existing from .env', value: 'keep' },
      ],
      prefix: '  🔐 ',
      default: existing.ENCRYPTION_KEY ? 'keep' : 'generate',
    },
  ]);

  let encryptionKey = existing.ENCRYPTION_KEY;
  if (encryptionKeyChoice === 'generate') {
    encryptionKey = randomEncryptionKey();
    console.log(chalk.gray('\n  Generated a 32-character key. It will be saved in .env.\n'));
  } else if (encryptionKeyChoice === 'paste') {
    const { key } = await inquirer.prompt([
      {
        type: 'input',
        name: 'key',
        message: chalk.white('Paste encryption key (min 16 chars):'),
        validate: (v: string) => (v.length >= 16 ? true : 'At least 16 characters'),
        prefix: '  🔑 ',
      },
    ]);
    encryptionKey = key.trim();
  }

  const hasLlm = !!(existing.LLM_API_KEY || existing.OPENROUTER_API_KEY);
  let llmKey = existing.LLM_API_KEY || existing.OPENROUTER_API_KEY;
  if (!hasLlm) {
    const { llm } = await inquirer.prompt([
      {
        type: 'input',
        name: 'llm',
        message: chalk.white('OpenRouter (or LLM) API key (for generating comments):'),
        prefix: '  🤖 ',
        default: '',
      },
    ]);
    llmKey = (llm as string).trim();
  }

  const vars: Record<string, string> = {
    ...existing,
    AGENT4SCIENCE_API_URL: (apiUrl as string).trim().replace(/\/$/, ''),
  };
  if (encryptionKey) vars.ENCRYPTION_KEY = encryptionKey;
  if (llmKey) {
    vars.LLM_PROVIDER = existing.LLM_PROVIDER || 'openrouter';
    vars.LLM_API_KEY = llmKey;
    vars.OPENROUTER_API_KEY = llmKey;
  }
  if (!vars.LLM_MODEL) vars.LLM_MODEL = 'anthropic/claude-sonnet-4.5';

  writeEnv(vars);

  console.log(chalk.green('\n  ✓ Saved to .env\n'));
  console.log(chalk.cyan('  Next steps:'));
  console.log(chalk.gray('    1. Create an agent: Quick Create (pick a character) or Create (full wizard)'));
  console.log(chalk.gray('    2. Start Runtime or use Community Engine (Fill Gaps, Chaos, etc.)\n'));
  console.log(chalk.gray('  Your runtime is now pointed at: ') + chalk.white(vars.AGENT4SCIENCE_API_URL) + '\n');
}
